name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test_runner:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.0, 3.1, 3.2, 3.3, 3.4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run non-Railtie tests
        run: |
          bundle exec ruby -Itest test/test_errormoji.rb
          bundle exec ruby -Itest test/unit/exception_patch_test.rb
          bundle exec ruby -Itest test/integration/load_test.rb

  railtie_runner:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Railtie integration test
        run: |
          bundle exec ruby -Itest test/integration/railtie_test.rb
          bundle exec ruby -Itest test/integration/railtie_exceptions_test.rb

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop

  test_verbose:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [3.4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run verbose test task
        run: bundle exec rake test:verbose
